services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flask_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - internal
      - external

networks:
  internal:
  external:

volumes:
  db_data:
